enum alphabetActions {

    ALPHABET_CREATE_REQUEST = "ALPHABET_CREATE_REQUEST",
    ALPHABET_CREATE_SUCCSESS = "ALPHABET_CREATE_SUCCSESS",
    ALPHABET_CREATE_FAIL = "ALPHABET_CREATE_FAIL",

    ALPHABET_EDIT_REQUEST = "ALPHABET_EDIT_REQUEST",
    ALPHABET_EDIT_SUCCSESS = "ALPHABET_EDIT_SUCCSESS",
    ALPHABET_EDIT_FAIL = "ALPHABET_EDIT_FAIL",

    ALPHABET_DELETE_REQUEST = "ALPHABET_DELETE_REQUEST",
    ALPHABET_DELETE_SUCCSESS = "ALPHABET_DELETE_SUCCSESS",
    ALPHABET_DELETE_FAIL = "ALPHABET_DELETE_FAIL",
}

export { alphabetActions }
