enum sequenceActions {

    SENTENCE_CREATE_REQUEST = "SENTENCE_CREATE_REQUEST",
    SENTENCE_CREATE_SUCCESS = "SENTENCE_CREATE_SUCCESS",
    SENTENCE_CREATE_FAIL = "SENTENCE_CREATE_FAIL",

}

export { sequenceActions };