enum sentenceActions {

    SENTENCE_CREATE_REQUEST = "SENTENCE_CREATE_REQUEST",
    SENTENCE_CREATE_SUCCESS = "SENTENCE_CREATE_SUCCESS",
    SENTENCE_CREATE_FAIL = "SENTENCE_CREATE_FAIL",
    SENTENCE_EDIT_REQUEST = "SENTENCE_EDIT_REQUEST",
    SENTENCE_EDIT_SUCCESS = "SENTENCE_EDIT_SUCCESS",
    SENTENCE_EDIT_FAIL = "SENTENCE_EDIT_FAIL",
    SENTENCE_DELETE_REQUEST = "SENTENCE_DELETE_REQUEST",
    SENTENCE_DELETE_SUCCESS = "SENTENCE_DELETE_SUCCESS",
    SENTENCE_DELETE_FAIL = "SENTENCE_DELETE_FAIL",

}

export { sentenceActions };